Repository With-Pet-Project/With-Pet-BE, pull requests merged in 2023-02, with the labels that each got.

#24 pet 관련 기능 구현
  src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/constants/ResponseConstants.java
  src/main/java/WebProject/withpet/common/dto/ApiErrorResponse.java
  src/main/java/WebProject/withpet/common/exception/DataNotFoundException.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
  src/main/java/WebProject/withpet/common/exception/UnauthorizedException.java
  src/main/java/WebProject/withpet/common/exception/UserNotFoundException.java
  src/main/java/WebProject/withpet/pets/controller/PetController.java
  src/main/java/WebProject/withpet/pets/domain/Pet.java
  src/main/java/WebProject/withpet/pets/domain/PetRepository.java
  src/main/java/WebProject/withpet/pets/dto/PetRequestDto.java
  src/main/java/WebProject/withpet/pets/dto/PetResponseDto.java
  src/main/java/WebProject/withpet/pets/service/PetService.java
  src/main/java/WebProject/withpet/users/domain/User.java
Labels: ✨ FEAT

#26 CI/CD 관련 세팅
  .gitignore
  scripts/deploy.sh
  src/main/resources/application.properties
Labels: ⚙️ CHORE

#27 Feat/kakao
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
  src/main/java/WebProject/withpet/users/dto/SocialLoginResponseDto.java
  src/main/java/WebProject/withpet/users/dto/SocialUserInfoDto.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ✨ FEAT

#28 fix: 인가 과정 버그 수정
  src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/common/auth/filter/JwtAuthorizationFilter.java
  src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
Labels: 🧙🏻 FIX

#30 refactor: 모든 응답이 ResponseEntity의 body에 담기도록 수정
  src/main/java/WebProject/withpet/pets/controller/PetController.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
Labels: ⚒ REFACTOR

#33 pet의 수정 권한 판단 레이어 변경
  src/main/java/WebProject/withpet/pets/service/PetService.java
  src/main/java/WebProject/withpet/users/domain/User.java
Labels: ⚒ REFACTOR

#34 BindingResult 를 통한 에러 핸들링 기능 및 ConstraintViolationException 에러 핸들링 기능 추가
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/dto/ApiErrorResponse.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
Labels: ✨ FEAT

#35 refactor: pet 의 유효성 검증이 dto 에서 이루어지도록 수정
  src/main/java/WebProject/withpet/pets/domain/Pet.java
  src/main/java/WebProject/withpet/pets/dto/PetRequestDto.java
Labels: ⚒ REFACTOR

#39 refactor: user 회원가입의 유효성 검증이 dto 에서 이루어지도록 수정
  src/main/java/WebProject/withpet/users/dto/UserRequestDto.java
Labels: ⚒ REFACTOR

#36 닉네임 중복 확인,비밀번호 변경, 회원탈퇴 추가 및 ConstraintViolationException 수정
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/constants/ResponseConstants.java
  src/main/java/WebProject/withpet/common/dto/ApiErrorResponse.java
  src/main/java/WebProject/withpet/common/dto/ApiResponse.java
  src/main/java/WebProject/withpet/common/exception/DuplicateException.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
  src/main/java/WebProject/withpet/users/domain/User.java
  src/main/java/WebProject/withpet/users/dto/ChangePasswordDto.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ⚒ REFACTOR, ✨ FEAT, ⚙️ CHORE

#42 chore: 토큰 관련 암호화 세팅
  src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java
Labels: ⚙️ CHORE

#40 feat: 챌린지 관련 기능 구현
  build.gradle
  src/main/java/WebProject/withpet/challenges/controller/ChallengeController.java
  src/main/java/WebProject/withpet/challenges/domain/Challenge.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLog.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepository.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepositoryCustom.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepositoryImpl.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeRepository.java
  src/main/java/WebProject/withpet/challenges/dto/ChallengeLogRequestDto.java
  src/main/java/WebProject/withpet/challenges/dto/ChallengeRequestDto.java
  src/main/java/WebProject/withpet/challenges/dto/DailyChallengeResponseDto.java
  src/main/java/WebProject/withpet/challenges/dto/WeeklyChallengeResponseDto.java
  src/main/java/WebProject/withpet/challenges/service/ChallengeLogService.java
  src/main/java/WebProject/withpet/challenges/service/ChallengeService.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
  src/main/java/WebProject/withpet/pets/domain/Pet.java
  src/main/java/WebProject/withpet/pets/service/PetService.java
  src/test/java/WebProject/withpet/challenges/ChallengeTest.java
Labels: ✨ FEAT, 🧙🏻 FIX

#45 fix: 프로퍼티를 읽어들이는 과정 오류 해결
  src/main/java/WebProject/withpet/challenges/controller/ChallengeController.java
  src/main/java/WebProject/withpet/challenges/domain/Challenge.java
  src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
  src/main/resources/application.properties
Labels: 🧙🏻 FIX

#47 feat: 토큰 유효성 검사 관련 기능 구현
  src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/common/auth/filter/JwtAuthorizationFilter.java
  src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
  src/main/java/WebProject/withpet/common/util/JwtUtil.java
Labels: ⚒ REFACTOR, ✨ FEAT

#49 feat: 건강관리 관련 기능 구현
  src/main/java/WebProject/withpet/pets/controller/HealthCareController.java
  src/main/java/WebProject/withpet/pets/domain/HealthCare.java
  src/main/java/WebProject/withpet/pets/domain/HealthCareRepository.java
  src/main/java/WebProject/withpet/pets/domain/HealthCareRepositoryCustom.java
  src/main/java/WebProject/withpet/pets/domain/HealthCareRepositoryImpl.java
  src/main/java/WebProject/withpet/pets/dto/HealthCareRequestDto.java
  src/main/java/WebProject/withpet/pets/dto/HealthCareResponseDto.java
  src/main/java/WebProject/withpet/pets/service/HealthCareService.java
Labels: ✨ FEAT

#50 refactor: 자주 사용되는 문자열 상수로 리팩토링
  src/main/java/WebProject/withpet/articles/controller/ArticleController.java
  src/main/java/WebProject/withpet/challenges/controller/ChallengeController.java
  src/main/java/WebProject/withpet/common/constants/ResponseConstants.java
  src/main/java/WebProject/withpet/common/constants/ResponseMessages.java
  src/main/java/WebProject/withpet/pets/controller/PetController.java
  src/main/java/WebProject/withpet/users/controller/MypageController.java
Labels: ⚒ REFACTOR
