Repository With-Pet-Project/With-Pet-BE, pull requests merged in 2023-03, with the labels that each got.

#57 feat: 가계부 crud 기능 구현
  src/main/java/WebProject/withpet/pets/controller/ConsumptionController.java
  src/main/java/WebProject/withpet/pets/domain/Consumption.java
  src/main/java/WebProject/withpet/pets/domain/ConsumptionRepository.java
  src/main/java/WebProject/withpet/pets/domain/ConsumptionRepositoryCustom.java
  src/main/java/WebProject/withpet/pets/domain/ConsumptionRepositoryImpl.java
  src/main/java/WebProject/withpet/pets/domain/Pet.java
  src/main/java/WebProject/withpet/pets/dto/ConsumptionRequestDto.java
  src/main/java/WebProject/withpet/pets/dto/ConsumptionResponseDto.java
  src/main/java/WebProject/withpet/pets/dto/MonthlyConsumptionByPetResponseDto.java
  src/main/java/WebProject/withpet/pets/dto/MonthlyConsumptionByUserResponseDto.java
  src/main/java/WebProject/withpet/pets/service/ConsumptionService.java
Labels: ⚒ REFACTOR, ✨ FEAT

#56 댓글 관련 CRUD 구현 및 피드백 반영/ 게시글,이미지 생성 관련 프론트 요구사항에 맞춰 변경
  src/main/java/WebProject/withpet/articles/controller/ArticleController.java
  src/main/java/WebProject/withpet/articles/controller/ImageController.java
  src/main/java/WebProject/withpet/articles/domain/Article.java
  src/main/java/WebProject/withpet/articles/domain/Comment.java
  src/main/java/WebProject/withpet/articles/dto/ArticleCreateRequestDto.java
  src/main/java/WebProject/withpet/articles/dto/CreateCommentRequestDto.java
  src/main/java/WebProject/withpet/articles/dto/ImageDto.java
  src/main/java/WebProject/withpet/articles/dto/ViewSpecificArticleResponseDto.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryCustom.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryImpl.java
  src/main/java/WebProject/withpet/articles/repository/ImageRepository.java
  src/main/java/WebProject/withpet/articles/service/ArticleService.java
  src/main/java/WebProject/withpet/articles/service/ImageService.java
  src/main/java/WebProject/withpet/articles/validation/ArticleValidator.java
  src/main/java/WebProject/withpet/comments/controller/CommentController.java
  src/main/java/WebProject/withpet/comments/domain/Comment.java
  src/main/java/WebProject/withpet/comments/dto/ViewCommentListDto.java
  src/main/java/WebProject/withpet/comments/dto/ViewCommentListResponseDto.java
  src/main/java/WebProject/withpet/comments/repository/CommentRepository.java
  src/main/java/WebProject/withpet/comments/repository/CommentRepositoryCustom.java
  src/main/java/WebProject/withpet/comments/repository/CommentRepositoryImpl.java
  src/main/java/WebProject/withpet/comments/service/CommentService.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
  src/main/java/WebProject/withpet/users/domain/User.java
  src/main/java/WebProject/withpet/users/dto/ViewMypageResponseDto.java
  src/main/java/WebProject/withpet/users/service/MypageService.java
  src/test/java/WebProject/withpet/comment/CommentServiceTest.java
Labels: ⚒ REFACTOR, ✨ FEAT, 🧙🏻 FIX

#67 API 테스트 중에 발생한 401에러 수정, 게시글 검색 api와 필터링 api를 하나로 통일에 따른 코드 수정, 게시글 삭제 구현
  src/main/java/WebProject/withpet/articles/controller/ArticleController.java
  src/main/java/WebProject/withpet/articles/domain/Article.java
  src/main/java/WebProject/withpet/articles/domain/SpecArticle.java
  src/main/java/WebProject/withpet/articles/dto/ViewArticleListDto.java
  src/main/java/WebProject/withpet/articles/dto/ViewArticleListRequestDto.java
  src/main/java/WebProject/withpet/articles/dto/ViewArticleListResponseDto.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepository.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryPagingCustomImpl.java
  src/main/java/WebProject/withpet/articles/service/ArticleLikeService.java
  src/main/java/WebProject/withpet/articles/service/ArticleService.java
  src/main/java/WebProject/withpet/articles/service/ImageService.java
  src/main/java/WebProject/withpet/comments/controller/CommentController.java
  src/main/java/WebProject/withpet/comments/service/CommentService.java
  src/main/java/WebProject/withpet/common/config/SecurityConfig.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
Labels: ⚒ REFACTOR, ✨ FEAT, 🧙🏻 FIX

#71 fix: 사용자의 소비내역 조회 시 모든 사용자의 소비내역이 나타나는 오류 해결 및 dto 수정에 따른 응답 형태 수정
  src/main/java/WebProject/withpet/pets/controller/ConsumptionController.java
  src/main/java/WebProject/withpet/pets/domain/ConsumptionRepositoryCustom.java
  src/main/java/WebProject/withpet/pets/domain/ConsumptionRepositoryImpl.java
  src/main/java/WebProject/withpet/pets/dto/MonthlyConsumptionsByUserResponseDto.java
  src/main/java/WebProject/withpet/pets/service/ConsumptionService.java
Labels: 🧙🏻 FIX

#72 프론트와 api 통신 과정에서 발견한 오류 해결 및 코드 리팩토링
  src/main/java/WebProject/withpet/articles/controller/ArticleController.java
  src/main/java/WebProject/withpet/articles/dto/ViewArticleDto.java
  src/main/java/WebProject/withpet/articles/dto/ViewArticleListResponseDto.java
  src/main/java/WebProject/withpet/articles/dto/ViewSpecificArticleResponseDto.java
  src/main/java/WebProject/withpet/articles/dto/ViewUserAndArticleResponseDto.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepository.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryCustom.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryImpl.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryPagingCustom.java
  src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryPagingCustomImpl.java
  src/main/java/WebProject/withpet/articles/service/ArticleService.java
  src/main/java/WebProject/withpet/common/config/SecurityConfig.java
  src/main/java/WebProject/withpet/users/controller/MypageController.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
  src/main/java/WebProject/withpet/users/domain/User.java
  src/main/java/WebProject/withpet/users/service/MypageService.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ⚒ REFACTOR, ✨ FEAT, 🧙🏻 FIX

#69 feat: 이메일 전송 기능 구현
  build.gradle
  src/main/java/WebProject/withpet/auth/controller/EmailController.java
  src/main/java/WebProject/withpet/auth/domain/ConfirmationToken.java
  src/main/java/WebProject/withpet/auth/domain/ConfirmationTokenRepository.java
  src/main/java/WebProject/withpet/auth/service/ConfirmationTokenService.java
  src/main/java/WebProject/withpet/auth/service/EmailService.java
  src/main/java/WebProject/withpet/auth/service/EmailServiceImpl.java
  src/main/java/WebProject/withpet/auth/util/ConfirmationKey.java
  src/main/java/WebProject/withpet/common/config/EmailConfig.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ✨ FEAT

#63 feat: refresh token 을 생성하는 기능 구현
  build.gradle
  src/main/java/WebProject/withpet/articles/controller/ArticleController.java
  src/main/java/WebProject/withpet/articles/controller/ArticleLikeController.java
  src/main/java/WebProject/withpet/auth/PrincipalDetails.java
  src/main/java/WebProject/withpet/auth/PrinicipalDetailsService.java
  src/main/java/WebProject/withpet/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/auth/controller/EmailController.java
  src/main/java/WebProject/withpet/auth/domain/ConfirmationToken.java
  src/main/java/WebProject/withpet/auth/domain/ConfirmationTokenRepository.java
  src/main/java/WebProject/withpet/auth/domain/RefreshToken.java
  src/main/java/WebProject/withpet/auth/domain/RefreshTokenRepository.java
  src/main/java/WebProject/withpet/auth/dto/TokenResponseDto.java
  src/main/java/WebProject/withpet/auth/filter/JwtAuthenticationFilter.java
  src/main/java/WebProject/withpet/auth/filter/JwtAuthorizationFilter.java
  src/main/java/WebProject/withpet/auth/service/ConfirmationTokenService.java
  src/main/java/WebProject/withpet/auth/service/EmailService.java
  src/main/java/WebProject/withpet/auth/service/EmailServiceImpl.java
  src/main/java/WebProject/withpet/auth/service/RefreshTokenService.java
  src/main/java/WebProject/withpet/auth/util/ConfirmationKey.java
  src/main/java/WebProject/withpet/auth/vo/LoginVo.java
  src/main/java/WebProject/withpet/challenges/controller/ChallengeController.java
  src/main/java/WebProject/withpet/comments/controller/CommentController.java
  src/main/java/WebProject/withpet/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/WebProject/withpet/common/config/EmailConfig.java
  src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java
  src/main/java/WebProject/withpet/common/config/SecurityConfig.java
  src/main/java/WebProject/withpet/common/config/WebConfig.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/util/JwtUtil.java
  src/main/java/WebProject/withpet/pets/controller/ConsumptionController.java
  src/main/java/WebProject/withpet/pets/controller/HealthCareController.java
  src/main/java/WebProject/withpet/pets/controller/PetController.java
  src/main/java/WebProject/withpet/users/controller/MypageController.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ⚒ REFACTOR, ✨ FEAT

#74 fix: 로그인 관련 필요하지 않은 세팅 제거
  src/main/java/WebProject/withpet/common/config/SecurityConfig.java
Labels: 🧙🏻 FIX

#83 feat: access token 만료 시 refresh token 을 이용하여 재발급받는 기능 구현
  src/main/java/WebProject/withpet/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/auth/controller/AccessTokenController.java
  src/main/java/WebProject/withpet/auth/filter/JwtAuthorizationFilter.java
  src/main/java/WebProject/withpet/auth/service/RefreshTokenService.java
  src/main/java/WebProject/withpet/auth/util/JwtUtil.java
  src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
  src/main/java/WebProject/withpet/common/exception/InvalidRefreshTokenException.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ✨ FEAT

#85 feat: 리프레시 토큰 유효기간에 따른 재발급 기능 구현
  src/main/java/WebProject/withpet/auth/application/JwtTokenProvider.java
  src/main/java/WebProject/withpet/auth/controller/AccessTokenController.java
  src/main/java/WebProject/withpet/auth/service/RefreshTokenService.java
  src/main/java/WebProject/withpet/auth/service/TokenService.java
  src/main/java/WebProject/withpet/auth/util/JwtUtil.java
  src/main/java/WebProject/withpet/users/controller/UserController.java
  src/main/java/WebProject/withpet/users/service/UserService.java
Labels: ✨ FEAT

#88 feat: 챌린지/챌린지 로그의 중복확인 및 에러핸들링 기능 구현
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepository.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepositoryCustom.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepositoryImpl.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeRepository.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeRepositoryCustom.java
  src/main/java/WebProject/withpet/challenges/domain/ChallengeRepositoryImpl.java
  src/main/java/WebProject/withpet/challenges/service/ChallengeLogService.java
  src/main/java/WebProject/withpet/challenges/service/ChallengeService.java
  src/main/java/WebProject/withpet/common/constants/ErrorCode.java
  src/main/java/WebProject/withpet/common/exception/DuplicateDateException.java
  src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
Labels: ⚒ REFACTOR, ✨ FEAT
